### ISSUE TITLE
Remove "OpenShift Login" as a Stage

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/jboss-eap-quickstarts#1]
It's been noted we might view this as too fine-grained as a stage here, though I'm not certain where else this step best fits as part of another stage.

  https://github.com/redhat-kontinuity/jboss-eap-quickstarts/blob/kontinu8/helloworld/.openshift-ci_cd/Jenkinsfile#L14

**Comment by tnozicka** [comment]
Ok, I will remove it and squash it under "Checkout SCM" stage. It needs to be right after it anyway because https://github.com/redhat-kontinuity/jboss-eap-quickstarts/blob/kontinu8/helloworld/.openshift-ci_cd/Jenkinsfile#L17 needs to be done ASAP.

**Comment by ALRubinger** [comment]
Thanks!
