### ISSUE TITLE
Add github webhooks support to pipelines

### ISSUE THREAD

**Issue by tnozicka** [redhat-kontinuity/jboss-eap-quickstarts#3]
Btw. it can be done even for local environments: https://blog.openshift.com/using-github-hooks-with-your-local-openshift-environment/

**Comment by tnozicka** [comment]
fixed by https://github.com/redhat-kontinuity/jboss-eap-quickstarts/commit/ecb306963fa07d7c4e511ac0af340dfa7877a4cf

**Comment by ALRubinger** [comment]
In concert with https://github.com/redhat-kontinuity/catapult/issues/138, https://github.com/redhat-kontinuity/catapult/issues/141, https://github.com/redhat-kontinuity/catapult/issues/142; I've verified this now works.
